### INCOMPLETE
# WORKS ONLY ON RH DISTRIBUTION
# MISSING APT PM
# MISSING CONFIGURATION
---
- name: "Configure NTP"
  hosts: linux_hosts
  become: yes
  tasks:
    - name: "Install required packages"
      yum:
        name: ntp
        state: latest
...