### UNCHECKED
---
- name: "Manage Users"
  hosts: linux_hosts
  vars:
    - users:
      - user01: "user01"
    - file: user_created_date.txt
  tasks:
    - name: "Create a new user"
      user:
        name: "{{ item }}"
        password: "{{ item }}"
      loop: "{{ users }}"
    - name: "Create file in users home"
      copy:
        dest: "/home/{{ item }}/{{ file }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0644
        content: "{{ ansible_date_time.iso8601 }}"
      loop: "{{ users }}"
...