### UNCHECKED
---
- name: "Manage Users"
  hosts: linux_hosts
  vars:
    - users:
      - user01:
          name: "user01"
          password: "qweASDzxc"
    - file: user_created_date.txt
  tasks:
    - name: "Create a new user"
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
      loop: "{{ users }}"
    - name: "Create file in users home"
      copy:
        dest: "/home/{{ item.name }}/{{ file }}"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: 0644
        content: "{{ ansible_date_time.iso8601 }}"
      loop: "{{ users }}"
...