---
- name: "Modules Playbook"
  hosts: fedora
  tasks:
    - name: "Run Module #1"
      my_first_module:
        name: John
        action: Run
      register: module_output
    - name: "Display Module Output #1"
      debug:
        var: module_output
    - name: "Run Module #2"
      my_first_module:
        name: Peter
      register: module_output
    - name: "Display Module Output #2"
      debug:
        var: module_output
    - name: "Run Module #3"
      my_first_module:
        name: Fail
      register: module_output
    - name: "Display Module Output #3"
      debug:
        var: module_output
...