---
- name: "Ansible Playbook"
  hosts: all
  tasks:
    - name: "Test Ping On Linux"
      ping:
      when: ansible_facts['system'] == "Linux"
    - name: "Test Ping on Windows"
      win_ping:
      when: ansible_facts['os_family'] == "Windows"
...
