---
- name: "Ansible Playbook"
  hosts: all
  tasks:
    - name: "Test Ping"
      ping:
      when: ansible_facts['system'] == "Linux"
    - name: "Test Ping"
      win_ping:
      when: ansible_facts['os_family'] == "Windows"
...
