---

- name: "PACKAGE | Install Required Packages"
  package:
    name:
      - dirmngr
      - python-apt
      - python3-apt
    state: latest

- name: "PACKAGE | Update Cache"
  package:
    update_cache=yes

- name: "PACKAGE | Update System"
  package:
    name: "*"
    state: latest

...