---

- name: "Install packages"
  yum:
    name: "{{ item }}"
    state: latest
  loop: 
    - mariadb-server
    - python3-PyMySQL

- name: create /root/.my.cnf with password credentials
  blockinfile:
    path: /root/.my.cnf
    block: |
      [client]
      user=root
      password={{ mysql_root_password }}

      [mysql]
      user=root
      password={{ mysql_root_password }}

      [mysqldump]
      user=root
      password={{ mysql_root_password }}

      [mysqldiff]
      user=root
      password={{ mysql_root_password }}
    create: yes

- name: "Start and enable mysql(mariadb) service"
  service:
    name: mariadb
    state: restarted
    enabled: yes

- name: "Create a database"
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_user: root
    login_password: ''

- name: "Create users"
  include_tasks: create_mariadb_user.yml
  loop: "{{ mysql_users }}"
  loop_control:
    loop_var: user

...