---

- name: "PACKAGE | Install Required Packages"
  package:
    name:
      - software-properties-common
      - dirmngr
      - python-mysqldb
      - python3-mysqldb
      - python-apt
      - python3-apt
    state: latest

...