---

- name: "Install packages"
  yum:
    name: "{{ item }}"
    state: latest
  loop: 
    - mariadb-server
    - python3-PyMySQL

- name: "Reset Root Password"
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"

- name: "Start and enable mysql(mariadb) service"
  service:
    name: mariadb
    state: started
    enabled: yes

- name: "Create a database"
  mysql_db:
    name: "{{ mysql_database }}"
    state: present

- name: "Create users"
  include_tasks: create_mariadb_user.yml
  loop: "{{ mysql_users }}"
  loop_control:
    loop_var: user

...