---
- name: "Install packages"
  yum:
    name: "{{ item }}"
    state: latest
  loop: 
    - mariadb-server
    - python3-PyMySQL
- name: "Start and enable mysql(mariadb) service"
  service:
    name: mariadb
    state: started
    enabled: yes
- name: "Test debug mysql database"
  debug:
    msg: "{{ mysql_database }}"
- name: "Create a database"
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
...