---

- name: "PACKAGE | Install Required Packages"
  package:
    name:
      - dirmngr
      - python-apt
      - python3-apt
    state: latest

- name: "PACKAGE | Update System"
  package:
    name: "*"
    state: latest

- name: "PACKAGE | Install MariaDB"
  package:
    name: mariadb-server
    state: latest

- name: Is root password set?
  command: mysql -u root --execute "SELECT NOW()"
  register: is_root_password_set
  ignore_errors: yes

- name: Set root password
  mysql_user:
    user=root
    password="{{ root_password }}"
    host=localhost
  when: is_root_password_set.rc == 0

- name: Set root password for other hosts
  mysql_user:
    user=root
    password="{{ root_password }}"
    host="{{item}}"
    login_user="root"
    login_host="localhost"
    login_password="{{ root_password }}"
  when: is_root_password_set.rc == 0
  with_items:
   - "127.0.0.1" 
   - "::1"

- name: Inform user of mysql root password
  debug:
    msg: "MariaDB root password was set to {{ root_password }}"
  when: is_root_password\set.rc == 0

- name: "SERVICE | Restart MariaDB"
  service:
    name: mariadb
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: "MYSQL | Create New Database"
  mysql_db:
    name: "{{ db_name }}"
    state: present

...